<?php
namespace api\controllers\v1;

use Yii;
use yii\base\Event;
use yii\rest\ActiveController;
use yii\web\Response;

class UserController extends ActiveController
{
    public $modelClass = 'common\models\user\User';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Event::on(Response::className(), Response::EVENT_BEFORE_SEND, [$this, 'beforeSend']);
    }

    public function beforeSend($event){
        //获取response,并配置输出格式为JSON
        $response = $event->sender;
        $response->format = Response::FORMAT_JSON;

        //处理返回信息
        if ($response->isSuccessful) {
            $code = 0;
            $message = "Success";
            $data = $response->data;
        }
        else {
            $code = $response->statusCode;
            $message = $response->data["message"];
            $data = null;
        }

        //自定义返回结构
        $response->statusCode = 200;
        $response->data = [
            'state' =>  [
                'code' => $code,
                'message' => $message,
            ],
            'data' => $data,
        ];
    }

    /**
     * 用户列表
     * @api {get} /v1/user list
     * @apiName list
     * @apiDescription 用户列表
     * @apiGroup User
     * @apiVersion 1.0.0
     *
     * @apiSuccess (200) {Number} id ID
     * @apiSuccess (200) {String} username 用户名
     * @apiSuccess (200) {String} email 邮箱
     * @apiSuccess (200) {Number} created_at 创建时间（时间戳）
     * @apiSuccess (200) {Number} created_at 更新时间（时间戳）
     *
     *
     * @apiSuccessExample 成功返回:
     * {
     *      "state":{
     *          "code":0,
     *          "massage":""
     *      },
     *      "data":[
     *          {"id":1,"username":"user","auth_key":"wD6zTurnBHhA4Z3mCYW0YDg2ydJkfPWy","password_hash":"$2y$13$h7N0xwgbNWVxLdLmXbVRkO5uCaccjBehHjppTNqAqmPCnDi/1.0UK","password_reset_token":null,"email":"user@yii.com","status":10,"created_at":1524535976,"updated_at":1524535976},
     *          {"id":2,"username":"user2","auth_key":"zFDjF_SSeQYc6eY7fEaGDFXcZBCDnse8","password_hash":"$2y$13$5YLa.bYAihZi6uW0LSI.fOQBcWPksCnAMhdOngd7Xx6uapGqbtH4u","password_reset_token":null,"email":"user2@yii.com","status":10,"created_at":1524552822,"updated_at":1524552822}
     *      ]
     * }
     *
     * @apiErrorExample 失败返回:
     * {
     *      "state":{
     *          "code":500,
     *          "massage":"fail."
     *      },
     *      "data":null
     * }
     *
     */

    /**
     * 用户信息
     * @api {get} /v1/user/:id detail
     * @apiName detail
     * @apiDescription 用户信息
     * @apiGroup User
     * @apiVersion 1.0.0
     *
     * @apiSuccess (200) {Number} id ID
     * @apiSuccess (200) {String} username 用户名
     * @apiSuccess (200) {String} email 邮箱
     * @apiSuccess (200) {Number} created_at 创建时间（时间戳）
     * @apiSuccess (200) {Number} created_at 更新时间（时间戳）
     *
     *
     * @apiSuccessExample 成功返回:
     * {
     *      "state":{
     *          "code":0,
     *          "massage":""
     *      },
     *      "data":{"id":1,"username":"user","auth_key":"wD6zTurnBHhA4Z3mCYW0YDg2ydJkfPWy","password_hash":"$2y$13$h7N0xwgbNWVxLdLmXbVRkO5uCaccjBehHjppTNqAqmPCnDi/1.0UK","password_reset_token":null,"email":"user@yii.com","status":10,"created_at":1524535976,"updated_at":1524535976}
     * }
     *
     * @apiErrorExample 失败返回:
     * {
     *      "state":{
     *          "code":500,
     *          "massage":"fail."
     *      },
     *      "data":null
     * }
     *
     */

    /**
     * 删除用户
     * @api {delete} /v1/user/:id delete
     * @apiName delete
     * @apiDescription 删除用户
     * @apiGroup User
     * @apiVersion 1.0.0
     *
     *
     * @apiSuccessExample 成功返回:
     * {
     *      "state":{
     *          "code":0,
     *          "massage":""
     *      },
     *      "data":null
     * }
     *
     * @apiErrorExample 失败返回:
     * {
     *      "state":{
     *          "code":500,
     *          "massage":"fail."
     *      },
     *      "data":null
     * }
     *
     */
}