<?php
namespace layui\field;

use yii\helpers\Html;
use layui\widgets\LayuiWidget;

class Edit extends LayuiInputWidget
{
    public function run()
    {
        //parent
        parent::run(); // TODO: Change the autogenerated stub

        //js
        $this->registerJs();

        //element
        $options = ["style"=>"display:none"];
        $element = Html::textarea($this->name,$this->value,$options);

        //return
        return $element;
    }

    public function registerJs(){
        $view = $this->getView();
        $view->registerJs('layui.use("layedit", function(){
            var layedit = layui.layedit;
            layedit.build("'.$this->id.'");
        });');
    }
}
