<?php
namespace layui\field;

use yii\helpers\Html;

/**
 * 使用方法：
 * <?= $form->field($model, 'data')->fileInput([
 *      "uploadUrl"=> yii\helpers\Url::to(['/upload/lay']),
 *      "btnText" => "上传文件",
 * ]) ?>
 */
class FileInput extends LayuiInputWidget
{
    public $btnId;
    public $uploadUrl;
    public $btnText = "上传文件";
    public $placeholder = "请上传文件";
    public $loadStyle = 1;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->btnId = uniqid();
    }

    public function run()
    {
        //parent
        parent::run(); // TODO: Change the autogenerated stub

        //js
        $this->registerJs();

        //element
        $input = $this->renderInput();
        $button = $this->renderButton();

        //return
        return $input.$button;
    }

    public function renderInput(){
        $options = [
            "id"=>$this->id,
            "readonly"=>true,
            //"placeholder"=>$this->model->getAttributeLabel($this->attribute),
            "placeholder"=>$this->placeholder,
            "class"=>"layui-select",
            "style"=>"max-width:100%"
        ];
        $input = Html::input("text",$this->name,$this->value,$options);
        return $input;
    }

    public function renderButton(){
        $options = [
            "id"=>$this->btnId,
            "class"=>"layui-btn",
            "style"=>"margin-bottom:2px"
        ];
        $i = Html::tag("i","&#xe67c;",["class"=>"layui-icon"]);
        $text = $this->btnText;
        $button = Html::button("$i$text",$options);
        return $button;
    }

    public function registerJs(){
        $view = $this->getView();
        $view->registerJs("
        layui.use('upload', function(){
            var upload = layui.upload;
            var load_index = null;
            upload.render({
                elem: '#$this->btnId',
                url: '$this->uploadUrl',
                accept: 'file',
                before:function(obj){
                    load_index = layer.load($this->loadStyle, {shade: false});
                },
                done: function(res, index, upload){
                    if(res.code == 0){
                        $('#$this->id').val(res.data.src);
                        $('#$this->id-show').text(res.data.src);
                    }
                    layer.close(load_index)
                }
            });
        });
        ");
    }
}
