<?php
namespace layui\field;

use yii\helpers\Html;

/**
 * 使用方法：
 * <?= $form->field($model, 'data')->imageInput([
 *      "uploadUrl"=> yii\helpers\Url::to(['/upload/lay']),
 *      "btnText" => "上传图片",
 * ]) ?>
 */
class ImageInput extends LayuiInputWidget
{
    public $btnId;
    public $uploadUrl;
    public $btnText = "上传图片";
    public $loadStyle = 1;
    public $width = 160;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->btnId = uniqid();
    }

    public function run()
    {
        //parent
        parent::run(); // TODO: Change the autogenerated stub

        //js
        $this->registerJs();

        //element

        $input = $this->renderInput();
        $button = $this->renderButton();
        $show = $this->renderShow();

        //return
        return $input.$button.$show;
    }

    public function renderInput(){
        $options = ["id"=>$this->id,];
        $input = Html::input("hidden",$this->name,$this->value,$options);
        return $input;
    }

    public function renderShow(){
        $width = $this->width."px";
        $image = $this->value ? Html::img($this->value,["style"=>"width:100%"]) : "";
        $options = ["id"=>"$this->btnId-show", "style"=>"width:$width;margin-top:6px"];
        $div = Html::tag("div", $image, $options);
        return $div;
    }

    public function renderButton(){
        $options = [
            "id"=>$this->btnId,
            "class"=>"layui-btn",
        ];
        $i = Html::tag("i","&#xe67c;",["class"=>"layui-icon"]);
        $text = $this->btnText;
        $button = Html::button("$i$text",$options);
        return $button;
    }

    public function registerJs(){
        $view = $this->getView();
        $view->registerJs("
        layui.use('upload', function(){
            var upload = layui.upload;
            var load_index = null;
            upload.render({
                elem: '#$this->btnId',
                url: '$this->uploadUrl',
                accept: 'image',
                before:function(obj){
                    load_index = layer.load($this->loadStyle, {shade: false});
                },
                done: function(res, index, upload){
                    if(res.code == 0){
                        $('#$this->id').val(res.data.src);
                        $('#$this->btnId-show').empty();
                        $('#$this->btnId-show').append('<img src=\"'+ res.data.src + '\" style=\"width:100%\">');
                    }
                    layer.close(load_index)
                }
            });
        });
        ");
    }
}
