<?php
namespace layui\widgets;

use yii\helpers\Html;
use yii\helpers\ArrayHelper;

/*
use metronic\widgets\ActiveForm
<?php $form = ActiveForm::begin([
    // 布局类型，参考Bootstrap：TYPE_HORIZONTAL、TYPE_VERTICAL、TYPE_INLINE
    "type"=>ActiveForm::TYPE_INLINE,
    // Separated风格：项分割线
    "separated"=>false,
    // Stripped风格：颜色相间
    "stripped"=>true,
    // Bordered风格：网格型
    "bordered"=>true,
    // 表单操作栏设置，即提交按钮等
    'buttons' => [
        Html::submit("Save",['class'=>'btn']),
        Html::button("Back",['class'=>'btn']),
    ]
]); ?>
<?php ActiveForm::end(); ?>
 */
class ActiveForm extends \yii\widgets\ActiveForm
{
    // Param
    public $inputCol = 4;
    public $buttons = [];
    public $pane = false;

    public function init()
    {
        //调用父结构函数
        parent::init(); // TODO: Change the autogenerated stub

        //加载JS
        $this->registerJs();

        //设置属性
        Html::addCssClass($this->options, 'layui-form');
        if($this->pane)
            Html::addCssClass($this->options, 'layui-form-pane');

        //设置字段属性
        if($this->pane) $options["pane"] = "";
        $this->fieldConfig = ArrayHelper::merge([
            'options'=>['class'=>'layui-form-item'],
            'labelOptions' => ['class' => 'layui-form-label'],
            'inputOptions' => ['class' => 'layui-input'],
            'template' => "{label}\n" . Html::tag('div', "{input}\n{error}\n{hint}", ['class' => "layui-input-block"]),
        ], $this->fieldConfig);

        //设置字段类
        if (!isset($this->fieldConfig['class']))
            $this->fieldConfig['class'] = ActiveField::className();

        //添加actions和form-body
        echo Html::beginTag('div', ['class' => 'form-body']);
    }

    public function run()
    {
        //闭合form-body和actions
        echo Html::endTag('div');

        //调用父结构函数
        parent::run(); // TODO: Change the autogenerated stub
    }

    public function registerJs(){
        $view = $this->getView();

        //失去焦点时设置值
        $view->registerJs('layui.use("form", function(){});');
    }

    public function submitButton($options=[]){
        Html::addCssClass($options,"layui-form-item");
        if($this->pane){
            $submit = Html::submitButton("提交",array_merge(["class"=>"layui-btn"]));
            $reset = Html::button("重置",["class"=>"layui-btn layui-btn-primary"]);
            $item = Html::tag("div","$submit\n$reset",$options);
        }
        else{
            $submit = Html::submitButton("提交",array_merge(["class"=>"layui-btn"]));
            $reset = Html::button("重置",["type"=>"reset","class"=>"layui-btn layui-btn-primary"]);
            $block = Html::tag("div","$submit\n$reset",['class'=>'layui-input-block']);
            $item = Html::tag("div",$block,$options);
        }
        echo $item;
    }
}
?>