<?php
namespace layui\widgets;

use yii\helpers\Html;

class Button extends LayuiWidget
{
    //tag
    const TAG_A = "a";
    const TAG_SUBMIT = "submit";
    const TAG_BUTTON = "button";

    //params
    public $text = '';
    public $icon = '';
    public $url = 'javascript:;';
    public $tag = self::TAG_BUTTON;
    public $theme = self::THEME_DEFAULT;
    public $size = self::SIZE_NORMAL;
    public $radius = false;
    public $disabled = false;
    public $options = [];

    /**
     * @return string
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        Html::addCssClass($this->options, "layui-btn");
        if ($this->theme)
            Html::addCssClass($this->options, "layui-btn-".$this->theme);
        if($this->size != self::SIZE_NORMAL)
            Html::addCssClass($this->options, "layui-btn-".$this->size);
        if ($this->radius)
            Html::addCssClass($this->options, "layui-btn-radius");
        if ($this->disabled)
            $this->options["disabled"] = "";

        $icon = empty($this->icon)?"":Html::tag("i",$this->icon,["class"=>"layui-icon"]);
        $content = empty($icon)?$this->text:"$this->text $icon";

        switch ($this->tag){
            case self::TAG_A:
                $button = Html::a($content,$this->url,$this->options);
                break;
            case self::TAG_SUBMIT:
                $button = Html::submitButton($content,$this->options);
                break;
            default:
                $button = Html::button($content,$this->options);
        }

        echo $button;
    }
}
?>