<?php
namespace layui\widgets;

use layui\LayuiAsset;
use yii\helpers\Html;

/*
use metronic\widgets\GridView
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        'id',
        'name',
        ['class' => 'metronic\widgets\ActionColumn'],
    ],
]); ?>
 */
class GridView extends \yii\grid\GridView
{
    //public $tableOptions = ['class'=>'layui-table layui-form'];

    public $layout='
            <div class="btable">
                {items}
                <div class="row">
                    <div class="col-md-5 col-sm-5">{summary}</div>
                    <div class="col-md-7 col-sm-7">{pager}</div></div>
                </div>
            </div>';

    public $pager=[
        'prevPageLabel'=>'<',
        'nextPageLabel'=>'>',
        //'firstPageLabel'=>"First",
        //'lastPageLabel'=>'Last',
        //'options'=>['class'=>'dataTables_paginate paging_bootstrap_full_number'],
    ];

    public function init()
    {
        LayuiAsset::register($this->view);
        parent::init(); // TODO: Change the autogenerated stub
    }
}
?>